config/routes.rb
Mobiloud::Application.routes.draw do
  resources :apps

  resources :users
  
  root to: 'users#index', as: 'users'

end

app/models/app.rb
class App < ActiveRecord::Base
  attr_accessible :color,:back_design, :background, :icon, :icon_design, :splash, :splash_design, :price, :status


  validates :app_name, :presence => {:message => "must be present"},
                       :uniqueness => {:message => "There is another app with that name"}
  validates :name_company, :presence => {:message => "must be present"}
  validates :color, :presence => {:message => "must be present"}
  
end


    
 

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name_company, :phone, :url, :address

  validates :url, :presence => true, :uniqueness => {:message => "This url is already used by another company"}
  validates :email, :presence => true, :uniqueness => {:message => "There is user with that email"}
  validates :name_company, :presence => {:message => "must be present"}
  validates :phone, :presence => {:message => "must be present"}
  validates :address, :presence => {:message => "must be present"}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apps }
    end
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
    @app = App.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/new
  # GET /apps/new.json
  def new
    @app = App.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/1/edit
  def edit
    @app = App.find(params[:id])
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = User.new

    @app.name_company = params[:name_company]
    @app.email = params[:email]
    @app.url = params[:url]
    @app.phone = params[:phone]
    @app.address = params[:address]

    # verify email format

    # salt password
  end

  # PUT /apps/1
  # PUT /apps/1.json
  def update
    @app = App.find(params[:id])

    respond_to do |format|
      if @app.update_attributes(params[:app])
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app = App.find(params[:id])
    @app.destroy

    respond_to do |format|
      format.html { redirect_to apps_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json

  def create
    @user = User.new

    @user.name_company = params[:name_company]
    @user.email = params[:email]
    @user.url = params[:url]
    @user.phone = params[:phone]
    @user.address = params[:address]

    # verify email format

    # salt password
  end


  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label : id_app %><br />
    <%= f.number_field : id_app %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.number_field :color %>
  </div>
  <div class="field">
    <%= f.label :background %><br />
    <%= f.text_field :background %>
  </div>
  <div class="field">
    <%= f.label :back_design %><br />
    <%= f.check_box :back_design %>
  </div>
  <div class="field">
    <%= f.label :icon %><br />
    <%= f.text_field :icon %>
  </div>
  <div class="field">
    <%= f.label :icon_design %><br />
    <%= f.text_field :icon_design %>
  </div>
  <div class="field">
    <%= f.label :splash %><br />
    <%= f.text_field :splash %>
  </div>
  <div class="field">
    <%= f.label :splash_design %><br />
    <%= f.text_field :splash_design %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :id_user %><br />
    <%= f.text_field :id_user %>
  </div>
  <div class="field">
    <%= f.label : %><br />
    <%= f.text_field : %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <tr>
    <th> id app</th>
    <th>Color</th>
    <th>Background</th>
    <th>Back design</th>
    <th>Icon</th>
    <th>Icon design</th>
    <th>Splash</th>
    <th>Splash design</th>
    <th>Status</th>
    <th>Price</th>
    <th>Id user</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apps.each do |app| %>
  <tr>
    <td><%= app. id_app %></td>
    <td><%= app.color %></td>
    <td><%= app.background %></td>
    <td><%= app.back_design %></td>
    <td><%= app.icon %></td>
    <td><%= app.icon_design %></td>
    <td><%= app.splash %></td>
    <td><%= app.splash_design %></td>
    <td><%= app.status %></td>
    <td><%= app.price %></td>
    <td><%= app.id_user %></td>
    <td><%= app. %></td>
    <td><%= link_to 'Show', app %></td>
    <td><%= link_to 'Edit', edit_app_path(app) %></td>
    <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b> id app:</b>
  <%= @app. id_app %>
</p>

<p>
  <b>Color:</b>
  <%= @app.color %>
</p>

<p>
  <b>Background:</b>
  <%= @app.background %>
</p>

<p>
  <b>Back design:</b>
  <%= @app.back_design %>
</p>

<p>
  <b>Icon:</b>
  <%= @app.icon %>
</p>

<p>
  <b>Icon design:</b>
  <%= @app.icon_design %>
</p>

<p>
  <b>Splash:</b>
  <%= @app.splash %>
</p>

<p>
  <b>Splash design:</b>
  <%= @app.splash_design %>
</p>

<p>
  <b>Status:</b>
  <%= @app.status %>
</p>

<p>
  <b>Price:</b>
  <%= @app.price %>
</p>

<p>
  <b>Id user:</b>
  <%= @app.id_user %>
</p>

<p>
  <b>:</b>
  <%= @app. %>
</p>


<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mobiloud</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label : id %><br />
    <%= f.number_field : id %>
  </div>
  <div class="field">
    <%= f.label :name_company %><br />
    <%= f.text_field :name_company %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= form_for(User.new, :url => {:action => "create", :controller => "users"}) do |f| %> 

<p>
<%= f.label :name_company %>
<%= f.text_field :name_company, :placeholder => 'Name of the company' %>
</p>
<p>
<%= f.label :email %>
<%= f.text_field :email, :placeholder => 'Contact Email' %> 
</p>
<p>
<%= f.label :pass %>
<%= f.password_field :pass, :placeholder => 'Password' %> 
</p>
<p>
<%= f.label :url %>
<%= f.text_field :url, :placeholder => 'URL of the company' %> 
</p>
<p>
<%= f.label :phone %>
<%= f.text_field :phone, :placeholder => 'URL of the company' %> 
</p>
<p>
<%= f.label :address %>
<%= f.text_field :address, :placeholder => 'URL of the company' %> 
</p>
<p>
<%= f.submit "Register" %>
</p>

<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b> id:</b>
  <%= @user. id %>
</p>

<p>
  <b>Name company:</b>
  <%= @user.name_company %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Url:</b>
  <%= @user.url %>
</p>

<p>
  <b>Phone:</b>
  <%= @user.phone %>
</p>

<p>
  <b>Address:</b>
  <%= @user.address %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>